"""Full-game SELF-PLAY collection (az_v9).

Plays entire ends from the canonical pre-placed openings with the CURRENT policy:
at every ply, a fresh KR-UCT search (same 2-ply/value-leaf recipe as collect.py's
tree branch) produces the policy-distillation target and the intended action; the
EXECUTED action is one execution-noise realisation of the intended one; the game
advances and the next ply is searched from wherever the realized play actually led.

One game of H plies yields H records (one per horizon, automatically balanced),
each anchored at a policy-induced state:
  * dist target      = soft-top-k over the searched root actions at that ply
  * value targets    = the game's realized final margin (grounded MC return), in
                       each state's to-move perspective — the AlphaZero value target
  * unroll targets   = the REAL game continuation (next K executed actions/states)
  * reward targets   = 2-step returns along the real trajectory (same convention as
                       collect.py's `_two_step_rewards`)

This differs from collect.py in the one way that matters for a compounding loop:
policy-improvement signal lands on states generated by the current policy's own
play (evolving each iteration), not on a frozen human-data root pool.

    JAX_PLATFORMS=cpu PYTHONPATH=src python -m world.search.selfplay \
        --config configs/exp_031_2ply_sims120.yaml --games 160 \
        --policy <p.pt> --value <v.pt> --value-world <world.pt> \
        --out artifacts/replay/mcts/az_v9_iter1/shard0.npz \
        --num-shards 4 --shard-id 0 --device cuda:0 --seed 900
"""
from __future__ import annotations

import argparse
from typing import Dict, List

import numpy as np

from .. import env_bridge
from ..config import Config, load_config
from ..preplaced import build_preplaced_roots
from ..replay.episode import build_unroll_record
from ..replay.schema import SOURCE_MCTS
from .collect import _live_np, _two_step_rewards


def play_game(root, policy, amean_t, astd_t, amean_np, astd_np, value_model,
              cfg, M, rng, device, noise, scorer="tree", diag=None,
              opponent=None, opponent_block=None):
    """Play one full end from `root` with search-at-every-ply. Returns the trajectory
    (states/conds/persps incl. terminal), executed actions, per-ply distillation
    targets, and the final margin in block-0 perspective.

    scorer="tree":     2-ply KR-UCT tree with value-head leaves (az_v9 recipe).
    scorer="terminal": VALUE-FREE dense-candidate operator (az_v10 / backward-induction
        recipe): `generate_candidates` (policy + structured + diverse + local + global)
        scored by noise-averaged MC rollouts to terminal + rule scoring
        (`search_state` with terminal_rollout_scoring=true). No learned V anywhere.
        If `diag` is a list, appends per-ply certification diagnostics:
        (horizon, Qbest_all - Qbest_policyOnly) — how much the dense proposal still
        improves on the policy's own samples under the value-free operator.
    scorer="tree_terminal": az_v11 — the classic MCTS shape, value-free: KR-UCT tree
        (visit-count adaptive allocation + progressive widening) to `mcts_max_depth`
        plies, with the ROOT pre-seeded by the dense `generate_candidates` proposal
        (eventual density) and leaves evaluated by on-policy MC rollout to terminal +
        rule scoring. No learned V anywhere. Same diag semantics as "terminal"
        (policy-subset = the first policy_candidates entries of the dense seed).
    scorer="screen_tree": az_v12 — two-stage, value-free, noise-robust (the EXP-013
        lesson restored): STAGE 1 screens the dense proposal with the flat batched
        terminal-MC operator at k_ego=noise_samples realisations per candidate
        (uniform precision); STAGE 2 refines only the top `screen_topk` survivors
        with a KR-UCT depth-`mcts_max_depth` tree with terminal-rollout leaves —
        mcts_sims over ~8 children gives each finalist ~6+ fresh-noise visits,
        adaptively allocated. Executed action + distill target come from stage-2 Q.
        diag entries: (horizon, stage1 margin, winner_from_policy_flag).
    """
    from csas.search import _sample_actions

    from .candidates import generate_candidates
    from .collect import _rollout_terminal_score, score_candidates_terminal, search_state
    from .kr_uct_tree import mcts_search

    sie = int(root.shots_in_end)
    st = root.x.copy().astype(np.float32)
    cc = root.c.copy().astype(np.float32)
    hh = int(root.horizon)
    states = [st.copy()]
    conds = [cc.copy()]
    persps = [int(round(cc[2]))]
    acts_exec: List[np.ndarray] = []
    dists: List = []

    def sample_fn(s, c2, n):
        return _sample_actions(policy, amean_t, astd_t, s, c2, n, device,
                               cfg.temperature, cfg.std_scale, 0.0)

    def rollout_value_fn(s, c2, h2, rp):
        if h2 <= 0:
            return float(env_bridge.score_end(s, rp))
        vp = int(round(c2[2]))
        v = float(env_bridge.evaluate_value(value_model, s[None], c2, device)[0])
        return v if vp == rp else -v

    while hh >= 1:
        if opponent is not None and int(round(cc[2])) == int(opponent_block):
            # EXP-065 asymmetric best-response mode: this block is played by a FIXED
            # opponent (deployed selection); no distillation target (conf=0), but the
            # ply still contributes matchup value/unroll targets.
            a_int = np.asarray(opponent.select_intended(st, cc, hh, sie, int(opponent_block)),
                               np.float32)
            dists.append((a_int[None].copy(), np.array([1.0], np.float32), 0.0))
            a = a_int
            if noise is not None:
                a = noise.sample_batch(a[None], 1).reshape(4).astype(np.float32)
            post, _ = env_bridge.apply_legality(st, env_bridge.simulate_one(st, cc, a)[None], hh, cc)
            acts_exec.append(a.copy())
            st = post[0]
            cc = env_bridge.next_condition(cc, sie)
            hh -= 1
            states.append(st.copy())
            conds.append(cc.copy())
            persps.append(int(round(cc[2])))
            continue
        if scorer == "terminal":
            res = search_state(policy, amean_t, astd_t, amean_np, astd_np, None,
                               st, cc, hh, sie, int(round(cc[2])),
                               cfg, rng, device, noise=noise)
            acts, q = res["cands"], res["q"]
            top_idx, weights = res["top_idx"], res["weights"]
            best = np.asarray(acts[int(res["best_idx"])], np.float32)
            if diag is not None:
                legal = q > -1e8
                n_pol = min(int(cfg.policy_candidates), len(q))
                lp = legal[:n_pol]
                if legal.any() and lp.any():
                    diag.append((int(hh), float(q[legal].max() - q[:n_pol][lp].max())))
        elif scorer in ("vectree", "opp_vectree"):
            # EXP-069: distillation targets from the VECTORISED 4-ply tree (EXP-068's
            # certified operator: monotone regret, beats flat width at >=16k on game
            # value). Terminal/rollout leaves only — no value head inside the tree.
            # EXP-074 opp_vectree: learner nodes still optimise, while explicit
            # opponent nodes integrate actions from the fixed opponent model.  The
            # first reply uses an affordable approximation of its deployed selector;
            # deeper nodes and the rollout tail follow its raw policy.  A free
            # minimiser is never substituted for the opponent being exploited.
            from csas.search import _sample_actions_batch
            from .collect import _mc_rollout_terminal_batch
            from .vec_tree import VecTree

            if scorer == "opp_vectree" and opponent is None:
                raise ValueError("opp_vectree requires --opponent-world or --opponent-mixture")

            def _sb(states, cond2, n):
                cb = np.broadcast_to(np.asarray(cond2, np.float32), (len(states), 3)).astype(np.float32)
                return np.asarray(_sample_actions_batch(policy, amean_t, astd_t,
                                                        np.asarray(states, np.float32), cb, n,
                                                        device, 1.1, 1.2, 0.0),
                                  np.float32).reshape(len(states), n, 4)

            def _rb(states, cond2, h2, persp2):
                def _opp_tail(ss, cb, h3, pb):
                    # The explicit tree nodes use deployed 48xK selection.  Past the
                    # depth cap, use the opponent's stochastic policy directly so a
                    # rollout remains affordable; the approximation is logged in the
                    # EXP-074 config and can later be replaced by a matchup V leaf.
                    return opponent.sample_intended_batch(ss, cb, 1)[:, 0, :]

                return _mc_rollout_terminal_batch(policy, amean_t, astd_t,
                                                  np.asarray(states, np.float32),
                                                  np.asarray(cond2, np.float32), int(h2), sie,
                                                  int(persp2), device, rng, noise,
                                                  cfg.rollout_temp, cfg.std_scale,
                                                  opponent_action_batch_fn=(
                                                      _opp_tail if scorer == "opp_vectree" else None),
                                                  opponent_block=(
                                                      int(opponent_block) if scorer == "opp_vectree" else None))

            def _ob(states, cond2, h2, depth2, n):
                cb = np.broadcast_to(np.asarray(cond2, np.float32),
                                     (len(states), 3)).astype(np.float32)
                if int(depth2) <= int(getattr(cfg, "opponent_model_deploy_depth", 1)):
                    return opponent.select_intended_batch(
                        np.asarray(states, np.float32), cb, int(h2), sie,
                        int(opponent_block), n_actions=int(n),
                        n_candidates=int(getattr(cfg, "opponent_model_candidates", 16)),
                        selection_noise_samples=int(getattr(
                            cfg, "opponent_model_noise_samples", 2)))
                return opponent.sample_intended_batch(
                    np.asarray(states, np.float32), cb, int(n))

            dense = np.asarray(generate_candidates(policy, amean_t, astd_t, st, cc, cfg, rng, device),
                               np.float32)
            n_pol = min(int(cfg.policy_candidates), len(dense))
            rest = dense[n_pol:]
            extra = rest[rng.choice(len(rest), size=min(32, len(rest)), replace=False)] if len(rest) else dense[:0]
            pool = np.concatenate([dense[:n_pol], extra])[:128]
            prior = np.concatenate([np.full(n_pol, 0.8 / n_pol),
                                    np.full(len(pool) - n_pol, 0.2 / max(len(pool) - n_pol, 1))])
            tree = VecTree(st, cc, hh, sie, pool, prior, sample_batch_fn=_sb, rollout_batch_fn=_rb,
                           noise=noise, rng=rng,
                           max_depth=int(getattr(cfg, "vectree_depth", 4)),
                           wave=32,
                           out_cap=int(getattr(cfg, "vectree_out_cap", 8)),
                           root_out_cap=int(getattr(cfg, "vectree_root_out_cap", 0)),
                           inner_pool=int(getattr(cfg, "vectree_inner_pool", 8)),
                           opponent_batch_fn=(_ob if scorer == "opp_vectree" else None),
                           opponent_block=(int(opponent_block) if scorer == "opp_vectree" else None),
                           opponent_samples=int(getattr(cfg, "opponent_model_actions", 1)))
            tree.run([int(getattr(cfg, "vectree_budget", 16000))])
            acts, q, se, n_vis = tree.root_stats()
            if len(acts) == 0:
                return None
            order = np.argsort(q)[::-1]
            top_idx, weights = env_bridge.soft_topk(q, min(M, len(q)), cfg.policy_temperature)
            conf = 1.0
            sig_t = float(getattr(cfg, "dist_sig_t", 0.0) or 0.0)
            if sig_t > 0.0 and len(q) >= 2:
                a_i, b_i = int(order[0]), int(order[1])
                den = float(np.sqrt(se[a_i] ** 2 + se[b_i] ** 2))
                conf = 1.0 if (np.isfinite(den) and den > 0 and (q[a_i] - q[b_i]) / den >= sig_t) else 0.0
            if diag is not None:
                diag.append((int(hh), float(conf)))
            dists.append((acts[top_idx].copy(), weights.copy(), conf))
            a = np.asarray(acts[int(order[0])], np.float32)
            if noise is not None:
                a = noise.sample_batch(a[None], 1).reshape(4).astype(np.float32)
            post, _ = env_bridge.apply_legality(st, env_bridge.simulate_one(st, cc, a)[None], hh, cc)
            acts_exec.append(a.copy())
            st = post[0]
            cc = env_bridge.next_condition(cc, sie)
            hh -= 1
            states.append(st.copy())
            conds.append(cc.copy())
            persps.append(int(round(cc[2])))
            continue
        elif scorer == "bigsel":
            # EXP-063: teacher = the deployed selection at big budget (EXP-062 T2):
            # pure policy proposals, k noisy executions each (CRN), value-head ranked.
            # Requires value_model (--value-world = incumbent value head).
            n_c = int(getattr(cfg, "bigsel_candidates", 192))
            ke = int(getattr(cfg, "bigsel_k", 64))
            cands = np.asarray(_sample_actions(policy, amean_t, astd_t, st, cc, n_c, device,
                                               float(getattr(cfg, "bigsel_temp", 1.1)),
                                               float(getattr(cfg, "bigsel_std", 1.2)), 0.0), np.float32)
            noisy = noise.sample_batch(cands, ke, crn=True).reshape(-1, 4)
            posts_all, ill_all = env_bridge.apply_legality(
                st, env_bridge.simulate(st, cc, noisy), hh, cc)
            if hh <= 1:
                qf = np.array([env_bridge.score_end(pp, int(round(cc[2]))) for pp in posts_all],
                              dtype=np.float64)
            else:
                nc2 = env_bridge.next_condition(cc, sie)
                qf = -env_bridge.evaluate_value(value_model, posts_all, nc2, device).astype(np.float64)
            q2 = qf.reshape(n_c, ke)
            q = q2.mean(axis=1)
            q_se = q2.std(axis=1, ddof=1) / np.sqrt(ke)
            q = env_bridge.mask_illegal_scores(q, ill_all.reshape(n_c, ke).any(axis=1))
            legal = q > -1e8
            if not legal.any():
                return None
            top_idx, weights = env_bridge.soft_topk(q, min(M, int(legal.sum())),
                                                    cfg.policy_temperature)
            order = np.argsort(np.where(legal, q, -1e18))[::-1]
            conf = 1.0
            sig_t = float(getattr(cfg, "dist_sig_t", 0.0) or 0.0)
            if sig_t > 0.0 and int(legal.sum()) >= 2:
                a_i, b_i = int(order[0]), int(order[1])
                gap = float(q[a_i] - q[b_i])
                se = float(np.sqrt(q_se[a_i] ** 2 + q_se[b_i] ** 2))
                conf = 1.0 if (se > 0 and gap / se >= sig_t) else 0.0
            if diag is not None:
                diag.append((int(hh), float(conf)))
            dists.append((cands[top_idx].copy(), weights.copy(), conf))
            a = np.asarray(cands[int(order[0])], np.float32)
            if noise is not None:
                a = noise.sample_batch(a[None], 1).reshape(4).astype(np.float32)
            post, _ = env_bridge.apply_legality(st, env_bridge.simulate_one(st, cc, a)[None], hh, cc)
            acts_exec.append(a.copy())
            st = post[0]
            cc = env_bridge.next_condition(cc, sie)
            hh -= 1
            states.append(st.copy())
            conds.append(cc.copy())
            persps.append(int(round(cc[2])))
            continue
        elif scorer == "stt":
            # EXP-058: flat screen scored by the searched+truncated estimator (EXP-056 StT
            # cell): value-greedy in-rollout steps (n_search) + champion-V leaf at trunc.
            # Requires value_model (--value-world = the incumbent's value head).
            cands = generate_candidates(policy, amean_t, astd_t, st, cc, cfg, rng, device)
            ke0 = int(getattr(cfg, "stt_k_ego", 4))
            stt_kw = dict(value_model=value_model, n_search=int(getattr(cfg, "stt_n_search", 6)),
                          max_steps=int(getattr(cfg, "stt_trunc", 4)), leaf_value_model=value_model)
            q, det_posts, det_illegal, q_se = score_candidates_terminal(
                policy, amean_t, astd_t, st, cc, cands, hh, sie, int(round(cc[2])),
                device, rng, noise, cfg.rollout_temp, cfg.std_scale,
                k_ego=ke0, return_std=True, crn=True, **stt_kw)
            q = env_bridge.mask_illegal_scores(q, det_illegal)
            legal = q > -1e8
            if not legal.any():
                return None
            smoothed = env_bridge.kr_smooth(cands, q, amean_np, astd_np,
                                            cfg.kernel_bandwidth, cfg.uct_c)
            smoothed = env_bridge.mask_illegal_scores(smoothed, det_illegal)
            top_idx, weights = env_bridge.soft_topk(smoothed, min(M, int(legal.sum())),
                                                    cfg.policy_temperature)
            order = np.argsort(np.where(legal, q, -1e18))[::-1]
            # collect-time significance gate (az_v13 machinery on the StT estimator)
            conf = 1.0
            sig_t = float(getattr(cfg, "dist_sig_t", 0.0) or 0.0)
            if sig_t > 0.0 and int(legal.sum()) >= 2:
                a_i, b_i = int(order[0]), int(order[1])
                gap = float(q[a_i] - q[b_i])
                se = float(np.sqrt(q_se[a_i] ** 2 + q_se[b_i] ** 2)) if q_se is not None else float("inf")
                t_stat = gap / se if se > 0 else 0.0
                lo = float(getattr(cfg, "dist_sig_lo", 0.8))
                if lo <= t_stat < sig_t:
                    ke1 = int(getattr(cfg, "dist_sig_extra_k", 16))
                    q_x, _, _, se_x = score_candidates_terminal(
                        policy, amean_t, astd_t, st, cc, cands[[a_i, b_i]], hh, sie,
                        int(round(cc[2])), device, rng, noise, cfg.rollout_temp, cfg.std_scale,
                        k_ego=ke1, return_std=True, crn=True, **stt_kw)
                    n_tot = ke0 + ke1
                    q_c = [(ke0 * q[i] + ke1 * q_x[j]) / n_tot for j, i in enumerate((a_i, b_i))]
                    se_c = [np.sqrt(ke0 ** 2 * q_se[i] ** 2 + ke1 ** 2 * se_x[j] ** 2) / n_tot
                            for j, i in enumerate((a_i, b_i))]
                    gap = float(q_c[0] - q_c[1])
                    se = float(np.sqrt(se_c[0] ** 2 + se_c[1] ** 2))
                    t_stat = gap / se if se > 0 else 0.0
                conf = 1.0 if t_stat >= sig_t else 0.0
            if diag is not None:
                diag.append((int(hh), float(conf)))
            dists.append((cands[top_idx].copy(), weights.copy(), conf))
            a = np.asarray(cands[int(order[0])], np.float32)
            if noise is not None:
                a = noise.sample_batch(a[None], 1).reshape(4).astype(np.float32)
            post, _ = env_bridge.apply_legality(st, env_bridge.simulate_one(st, cc, a)[None], hh, cc)
            acts_exec.append(a.copy())
            st = post[0]
            cc = env_bridge.next_condition(cc, sie)
            hh -= 1
            states.append(st.copy())
            conds.append(cc.copy())
            persps.append(int(round(cc[2])))
            continue
        elif scorer == "screen_tree":
            # ---- stage 1: noise-robust flat screen over the dense proposal ----
            res1 = search_state(policy, amean_t, astd_t, amean_np, astd_np, None,
                                st, cc, hh, sie, int(round(cc[2])),
                                cfg, rng, device, noise=noise)
            cands1, q1 = res1["cands"], res1["q"]
            legal1 = q1 > -1e8
            n_pol = min(int(cfg.policy_candidates), len(q1))
            if diag is not None and legal1.any() and legal1[:n_pol].any():
                m1 = float(q1[legal1].max() - q1[:n_pol][legal1[:n_pol]].max())
            else:
                m1 = None
            k_surv = min(int(getattr(cfg, "screen_topk", 8)), int(legal1.sum()))
            if k_surv < 1:
                return None
            order = np.argsort(np.where(legal1, q1, -1e18))[::-1][:k_surv]
            survivors = cands1[order]
            surv_from_policy = order < n_pol

            # ---- collect-time significance test (az_v13): distill this ply only if the
            # screen's top-1 vs top-2 preference is statistically real (t-test on the MC
            # means), with a batched tie-break round in the ambiguous band. ----
            conf = 1.0
            sig_t = float(getattr(cfg, "dist_sig_t", 0.0) or 0.0)
            if sig_t > 0.0 and k_surv >= 2:
                q_se1 = res1.get("q_se")
                a, b = int(order[0]), int(order[1])
                gap = float(q1[a] - q1[b])
                se = float(np.sqrt(q_se1[a] ** 2 + q_se1[b] ** 2)) if q_se1 is not None else float("inf")
                t_stat = gap / se if se > 0 else 0.0
                lo = float(getattr(cfg, "dist_sig_lo", 0.8))
                if lo <= t_stat < sig_t:
                    # tie-break: extra realisations for the top-2, then pool with stage-1 stats
                    ke0 = int(cfg.noise_samples)
                    ke1 = int(getattr(cfg, "dist_sig_extra_k", 16))
                    q_x, _, _, se_x = score_candidates_terminal(
                        policy, amean_t, astd_t, st, cc, cands1[[a, b]], hh, sie,
                        int(round(cc[2])), device, rng, noise, cfg.rollout_temp, cfg.std_scale,
                        value_model=None, n_search=1, k_ego=ke1, return_std=True)
                    n_tot = ke0 + ke1
                    q_c = [(ke0 * q1[i] + ke1 * q_x[j]) / n_tot for j, i in enumerate((a, b))]
                    se_c = [np.sqrt(ke0 ** 2 * q_se1[i] ** 2 + ke1 ** 2 * se_x[j] ** 2) / n_tot
                            for j, i in enumerate((a, b))]
                    gap = float(q_c[0] - q_c[1])
                    se = float(np.sqrt(se_c[0] ** 2 + se_c[1] ** 2))
                    t_stat = gap / se if se > 0 else 0.0
                conf = 1.0 if t_stat >= sig_t else 0.0

            # ---- stage 2: KR-UCT depth-capped refinement tree over the survivors ----
            def rollout_value_fn(s, c2, h2, rp):
                if h2 <= 0:
                    return float(env_bridge.score_end(s, rp))
                return _rollout_terminal_score(policy, amean_t, astd_t, s, c2, h2, sie, rp,
                                               device, noise, cfg.rollout_temp, cfg.std_scale)

            res2 = mcts_search(st, cc, hh, sie, int(round(cc[2])),
                               sample_fn=sample_fn, rollout_value_fn=rollout_value_fn,
                               action_mean=amean_np, action_std=astd_np,
                               n_sims=int(cfg.mcts_sims),
                               k_widen=cfg.mcts_k_widen, alpha_widen=cfg.mcts_alpha_widen,
                               kernel_bw=cfg.kernel_bandwidth, uct_c=cfg.mcts_uct_c,
                               noise=noise, rng=rng,
                               max_depth=int(getattr(cfg, "mcts_max_depth", 0)),
                               max_children=k_surv,       # tree restricted to the survivors
                               root_candidates=survivors)
            acts, q2, nvis = res2["actions"], res2["q"], res2["n"]
            visited = nvis > 0
            if not visited.any():
                return None
            top_idx, weights = env_bridge.soft_topk(
                np.where(visited, q2, -1e9), min(M, int(visited.sum())), cfg.policy_temperature)
            w_idx = int(np.argmax(np.where(visited, q2, -1e9)))
            best = np.asarray(acts[w_idx], np.float32)
            if diag is not None and m1 is not None:
                winner_pol = bool(surv_from_policy[w_idx]) if w_idx < len(surv_from_policy) else False
                diag.append((int(hh), m1, int(winner_pol)))
            dists.append((acts[top_idx].copy(), weights.copy(), conf))
            a = best
            if noise is not None:
                a = noise.sample_batch(a[None], 1).reshape(4).astype(np.float32)
            post, _ = env_bridge.apply_legality(st, env_bridge.simulate_one(st, cc, a)[None], hh, cc)
            acts_exec.append(a.copy())
            st = post[0]
            cc = env_bridge.next_condition(cc, sie)
            hh -= 1
            states.append(st.copy())
            conds.append(cc.copy())
            persps.append(int(round(cc[2])))
            continue
        elif scorer == "tree_terminal":
            dense = generate_candidates(policy, amean_t, astd_t, st, cc, cfg, rng, device)

            def rollout_value_fn(s, c2, h2, rp):
                if h2 <= 0:
                    return float(env_bridge.score_end(s, rp))
                return _rollout_terminal_score(policy, amean_t, astd_t, s, c2, h2, sie, rp,
                                               device, noise, cfg.rollout_temp, cfg.std_scale)

            res = mcts_search(st, cc, hh, sie, int(round(cc[2])),
                              sample_fn=sample_fn, rollout_value_fn=rollout_value_fn,
                              action_mean=amean_np, action_std=astd_np,
                              n_sims=int(cfg.mcts_sims),
                              k_widen=cfg.mcts_k_widen, alpha_widen=cfg.mcts_alpha_widen,
                              kernel_bw=cfg.kernel_bandwidth, uct_c=cfg.mcts_uct_c,
                              noise=noise, rng=rng,
                              max_depth=int(getattr(cfg, "mcts_max_depth", 0)),
                              max_children=max(48, len(dense)),
                              root_candidates=dense)
            acts, q, nvis = res["actions"], res["q"], res["n"]
            if len(acts) == 0:
                return None
            visited = nvis > 0
            top_idx, weights = env_bridge.soft_topk(
                np.where(visited, q, -1e9), min(M, int(visited.sum())), cfg.policy_temperature)
            best = np.asarray(acts[int(np.argmax(np.where(visited, q, -1e9)))], np.float32)
            if diag is not None:
                n_pol = min(int(cfg.policy_candidates), len(q))
                vp = visited[:n_pol]
                if visited.any() and vp.any():
                    diag.append((int(hh), float(q[visited].max() - q[:n_pol][vp].max())))
        else:
            res = mcts_search(st, cc, hh, sie, int(round(cc[2])),
                              sample_fn=sample_fn, rollout_value_fn=rollout_value_fn,
                              action_mean=amean_np, action_std=astd_np,
                              n_sims=int(cfg.mcts_sims),
                              k_widen=cfg.mcts_k_widen, alpha_widen=cfg.mcts_alpha_widen,
                              kernel_bw=cfg.kernel_bandwidth, uct_c=cfg.mcts_uct_c,
                              noise=noise, rng=rng,
                              max_depth=int(getattr(cfg, "mcts_max_depth", 0)))
            acts, q = res["actions"], res["q"]
            if len(acts) == 0:
                return None
            top_idx, weights = env_bridge.soft_topk(q, min(M, len(q)), cfg.policy_temperature)
            best = np.asarray(acts[int(np.argmax(q))], np.float32)
        dists.append((acts[top_idx].copy(), weights.copy()))

        a = best
        if noise is not None:  # realized execution = one noise sample of the intended shot
            a = noise.sample_batch(a[None], 1).reshape(4).astype(np.float32)
        post, _ = env_bridge.apply_legality(st, env_bridge.simulate_one(st, cc, a)[None], hh, cc)
        acts_exec.append(a.copy())
        st = post[0]
        cc = env_bridge.next_condition(cc, sie)
        hh -= 1
        states.append(st.copy())
        conds.append(cc.copy())
        persps.append(int(round(cc[2])))

    m0 = float(env_bridge.score_end(st, 0))   # realized final margin, block-0 perspective
    return states, conds, persps, acts_exec, dists, m0


def records_from_game(states, conds, persps, acts_exec, dists, m0,
                      K, M, value_model, device, collect_reward) -> List[Dict[str, np.ndarray]]:
    """One record per ply. Value targets = realized final margin, per-state perspective
    (same sign convention as collect.py's tree branch). Unroll = the real continuation.
    A dists entry may be (actions, weights) or (actions, weights, conf) — conf in [0,1]
    multiplies the record's dist_mask (collect-time significance gating, az_v13)."""
    recs = []
    L = len(acts_exec)
    for t in range(L):
        p = persps[t]
        margin_p = m0 if p == 0 else -m0
        k_eff = min(K, L - t)
        vt = np.array([margin_p if persps[t + j] == p else -margin_p
                       for j in range(k_eff + 1)], np.float32)
        if collect_reward:
            rew = _two_step_rewards(states[t:], conds[t:], persps[t:],
                                    margin_p, p, value_model, device)[:k_eff]
        else:
            rew = np.zeros((k_eff,), np.float32)
        entry = dists[t]
        da, dw = entry[0], entry[1]
        conf = float(entry[2]) if len(entry) > 2 else 1.0
        rec = build_unroll_record(
            K, M, x0=states[t], c0=conds[t],
            actions_raw=np.array(acts_exec[t:t + k_eff], np.float32),
            next_states=np.array(states[t + 1:t + k_eff + 1], np.float32),
            next_conds=np.array(conds[t + 1:t + k_eff + 1], np.float32),
            value_targets=vt, rewards=np.asarray(rew, np.float32),
            outcome_margin=float(margin_p), source=SOURCE_MCTS, horizon=L - t,
            dist_actions_raw=da, dist_weights=dw, live_mask_fn=_live_np)
        rec["dist_mask"] = np.float32(float(rec["dist_mask"]) * conf)
        recs.append(rec)
    return recs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=None)
    ap.add_argument("--games", type=int, default=160, help="games for THIS shard")
    ap.add_argument("--policy", required=True)
    ap.add_argument("--value", required=True)
    opp = ap.add_mutually_exclusive_group()
    opp.add_argument("--opponent-world", default=None,
                     help="EXP-065: fixed-opponent ckpt (deployed 48x8 selection) playing one block per game; learner plies get targets, values become matchup returns")
    opp.add_argument("--opponent-mixture", default=None,
                     help="JSON manifest of {members:[{name, checkpoint, weight}]} sampled once per game")
    ap.add_argument("--value-world", default=None,
                    help="WorldModel ckpt: its value head evaluates tree leaves "
                         "(closes the V-improves-search loop). Overrides --value.")
    ap.add_argument("--out", required=True)
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--split", default="train")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--num-shards", type=int, default=1)
    ap.add_argument("--shard-id", type=int, default=0)
    ap.add_argument("--scorer", choices=["tree", "terminal", "tree_terminal", "screen_tree", "stt", "bigsel", "vectree", "opp_vectree"], default="tree",
                    help="tree = 2-ply KR-UCT with value-head leaves (az_v9); "
                         "terminal = value-free dense-candidate MC-to-terminal operator (az_v10); "
                         "tree_terminal = dense-root KR-UCT to mcts_max_depth + terminal-rollout leaves (az_v11); "
                         "screen_tree = noise-robust flat screen -> depth-2 tree over survivors (az_v12); "
                         "stt = searched+truncated rollout estimator screen (EXP-056/058; needs --value-world)")
    args = ap.parse_args()

    import torch
    from csas.search import load_policy

    cfg: Config = load_config(args.config) if args.config else Config()
    device = torch.device(args.device)
    torch.manual_seed(int(args.seed) + 17)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(int(args.seed) + 17)
    env_bridge.warm_jax()
    print(f"[selfplay] RULES: boundary_removal={'ON (real takeout rules)' if env_bridge.BOUNDARY_REMOVAL else 'OFF (HISTORICAL convention!)'}",
          flush=True)
    policy, amean_t, astd_t = load_policy(args.policy, device)
    amean_np = amean_t.detach().cpu().numpy().astype(np.float64)
    astd_np = astd_t.detach().cpu().numpy().astype(np.float64)

    if args.value_world:
        import torch.nn as nn

        from ..config import model_cfg_from_dict
        from ..model import WorldModel
        from ..train.trainer import load_world_checkpoint

        ck = torch.load(args.value_world, map_location=device, weights_only=False)
        _wm = WorldModel(model_cfg_from_dict(ck["model_cfg"])).to(device)
        load_world_checkpoint(_wm, args.value_world, map_location=device)
        _wm.eval()

        class _WorldValue(nn.Module):
            def __init__(self, m): super().__init__(); self.m = m
            def forward(self, x, c): return self.m.value(self.m.encode(x, c))

        value_model = _WorldValue(_wm)
        print(f"[selfplay] tree leaves = INCUMBENT world value head ({args.value_world})", flush=True)
    else:
        value_model = env_bridge.load_csas_value(args.value, device)
        print(f"[selfplay] tree leaves = frozen csas value ({args.value})", flush=True)

    H = int(cfg.horizon.max_horizon)
    roots = build_preplaced_roots(H, args.games, args.split, args.seed,
                                  num_shards=args.num_shards, shard_id=args.shard_id,
                                  balance=True)
    rng = np.random.default_rng(args.seed + 7919)
    K, M = cfg.replay.unroll_steps, cfg.search.soft_topk

    from .noise import make_noise
    noise = make_noise(cfg.search.noise_config, args.seed + 31) if cfg.search.noise_samples > 0 else None
    if noise is not None:
        print(f"[selfplay] execution noise ON: {cfg.search.noise_config}", flush=True)
    collect_reward = bool(getattr(cfg.search, "collect_step_reward", False))

    opponent = None
    opponents = []
    opponent_weights = None
    opponent_names = []
    if args.opponent_world:
        from ..eval.head_to_head import WorldPlayer
        opponent = WorldPlayer(args.opponent_world, device, name="fixed_opponent",
                               noise=make_noise(cfg.search.noise_config, args.seed + 977),
                               sel_noise_samples=8)
        opponents = [opponent]
        opponent_weights = np.array([1.0], dtype=np.float64)
        opponent_names = ["fixed_opponent"]
        print(f"[selfplay] BR mode: fixed opponent = {args.opponent_world} (deployed 48x8)", flush=True)
    elif args.opponent_mixture:
        import json
        from pathlib import Path

        from ..eval.head_to_head import WorldPlayer

        mix_path = Path(args.opponent_mixture)
        spec = json.loads(mix_path.read_text())
        members = list(spec.get("members", []))
        if not members:
            raise ValueError(f"opponent mixture has no members: {mix_path}")
        weights = np.asarray([float(m["weight"]) for m in members], dtype=np.float64)
        if not np.isfinite(weights).all() or (weights < 0).any() or weights.sum() <= 0:
            raise ValueError(f"invalid opponent mixture weights in {mix_path}: {weights}")
        opponent_weights = weights / weights.sum()
        for j, member in enumerate(members):
            ckpt = Path(member["checkpoint"])
            if not ckpt.is_absolute():
                ckpt = (mix_path.parent / ckpt).resolve()
                if not ckpt.exists():
                    ckpt = Path(member["checkpoint"]).resolve()
            if not ckpt.exists():
                raise FileNotFoundError(f"opponent checkpoint not found: {member['checkpoint']}")
            name = str(member.get("name", ckpt.stem))
            opponents.append(WorldPlayer(
                str(ckpt), device, name=name,
                noise=make_noise(cfg.search.noise_config, args.seed + 977 + 1009 * j),
                sel_noise_samples=int(spec.get("selection_noise_samples", 8))))
            opponent_names.append(name)
        print("[selfplay] BR mixture: " + ", ".join(
            f"{n}={w:.3%}" for n, w in zip(opponent_names, opponent_weights)), flush=True)

    recs: List[Dict[str, np.ndarray]] = []
    diag: List = [] if args.scorer in ("terminal", "tree_terminal", "screen_tree", "stt", "bigsel", "vectree", "opp_vectree") else None
    n_games = 0
    opponent_counts = {name: 0 for name in opponent_names}
    opponent_rng = np.random.default_rng(args.seed + 104729)
    for i, root in enumerate(roots):
        if opponents:
            oi = int(opponent_rng.choice(len(opponents), p=opponent_weights))
            opponent = opponents[oi]
            opponent_counts[opponent_names[oi]] += 1
        g = play_game(root, policy, amean_t, astd_t, amean_np, astd_np,
                      value_model, cfg.search, M, rng, device, noise,
                      scorer=args.scorer, diag=diag,
                      opponent=opponent,
                      opponent_block=(i % 2) if opponent is not None else None)
        if g is None:
            continue
        states, conds, persps, acts_exec, dists, m0 = g
        recs.extend(records_from_game(states, conds, persps, acts_exec, dists, m0,
                                      K, M, value_model, device, collect_reward))
        n_games += 1
        if n_games % 10 == 0:
            print(f"[selfplay] {n_games}/{len(roots)} games ({len(recs)} records)", flush=True)

    from ..replay.buffers import save_shard
    n = save_shard(args.out, recs)
    print(f"[selfplay] wrote {n} records from {n_games} games -> {args.out}", flush=True)

    # provenance manifest: everything needed to know whether this shard can be reused
    # in a future experiment without re-collecting.
    import json as _json
    import os as _os
    import time as _time
    s = cfg.search
    manifest = dict(
        created_utc=_time.strftime("%Y-%m-%dT%H:%M:%SZ", _time.gmtime()),
        records=int(n), games=int(n_games),
        scorer=args.scorer, seed=int(args.seed),
        num_shards=int(args.num_shards), shard_id=int(args.shard_id), split=args.split,
        policy_ckpt=args.policy, policy_mtime=_os.path.getmtime(args.policy),
        value_world=args.value_world,
        config=args.config,
        opponent_world=args.opponent_world,
        opponent_mixture=args.opponent_mixture,
        opponent_sample_counts=opponent_counts,
        search=dict(policy_candidates=s.policy_candidates, structured=s.structured_candidates,
                    diverse=s.diverse_candidates, local=s.local_candidates, global_=s.global_candidates,
                    noise_samples=s.noise_samples, noise_config=s.noise_config,
                    use_mcts_tree=s.use_mcts_tree, mcts_sims=s.mcts_sims,
                    mcts_max_depth=int(getattr(s, "mcts_max_depth", 0)),
                    mcts_k_widen=s.mcts_k_widen,
                    terminal_rollout_scoring=bool(getattr(s, "terminal_rollout_scoring", False)),
                    value_leaf_bootstrap=bool(getattr(s, "value_leaf_bootstrap", False)),
                    screen_topk=int(getattr(s, "screen_topk", 0)),
                    vectree_budget=int(getattr(s, "vectree_budget", 0)),
                    vectree_depth=int(getattr(s, "vectree_depth", 0)),
                    vectree_root_out_cap=int(getattr(s, "vectree_root_out_cap", 0)),
                    opponent_model_actions=int(getattr(s, "opponent_model_actions", 1)),
                    opponent_model_deploy_depth=int(getattr(s, "opponent_model_deploy_depth", 1)),
                    opponent_model_candidates=int(getattr(s, "opponent_model_candidates", 16)),
                    opponent_model_noise_samples=int(getattr(s, "opponent_model_noise_samples", 2)),
                    opponent_tail="raw_policy" if args.scorer == "opp_vectree" else None,
                    rollout_temp=s.rollout_temp, soft_topk=s.soft_topk,
                    policy_temperature=s.policy_temperature),
    )
    with open(args.out.replace(".npz", ".manifest.json"), "w") as fh:
        _json.dump(manifest, fh, indent=2)
    if diag is not None:
        import json
        by_h, by_h_wp = {}, {}
        for entry in diag:
            h, m = entry[0], entry[1]
            by_h.setdefault(h, []).append(m)
            if len(entry) > 2:
                by_h_wp.setdefault(h, []).append(entry[2])
        summary = {}
        for h, v in sorted(by_h.items()):
            s = dict(n=len(v), mean_margin=float(np.mean(v)),
                     p90_margin=float(np.percentile(v, 90)),
                     frac_positive=float(np.mean(np.asarray(v) > 0)))
            if h in by_h_wp:
                s["frac_winner_from_policy"] = float(np.mean(by_h_wp[h]))
            summary[f"h{h:02d}"] = s
        with open(args.out.replace(".npz", ".diag.json"), "w") as fh:
            json.dump(summary, fh, indent=2)
        print(f"[selfplay] certification diagnostics -> {args.out.replace('.npz', '.diag.json')}", flush=True)


if __name__ == "__main__":
    main()
